version: "3.7"

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017

  application:
    image: stupic
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: npm start